<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Dominic Royé">
<meta name="dcterms.date" content="2026-03-02">
<title>Downscaling solar radiation in the Canary Islands with GAM – Dr Dominic Royé</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<link href="../../assets/img/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ffd63aee3bc7b1a5c22a514ee9a46f80.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-81759bfceaa241ed514e8c3c2c4ac429.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/quarto-contrib/fontawesome6-6.7.2/all.min.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/fontawesome6-6.7.2/latex-fontsize.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/academicons-1.9.4/all.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/academicons-1.9.4/size.css" rel="stylesheet">
<script src="../../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-NK2N7F46NB"></script><script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-NK2N7F46NB', { 'anonymize_ip': true});
</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
<meta name="twitter:title" content="Downscaling solar radiation in the Canary Islands with GAM">
<meta name="twitter:description" content="Researcher in climate science at MBG-CSIC">
<meta name="twitter:image" content="https://dominicroye.github.io/blog/canary-gam-downscaling/featured.png">
<meta name="twitter:creator" content="@drxeo.eu">
<meta name="twitter:site" content="@drxeo.eu">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image-height" content="3000">
<meta name="twitter:image-width" content="3000">
</head>
<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg " data-bs-theme="dark"><div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../assets/img/logo.svg" alt="" class="navbar-logo light-content"><img src="../../assets/img/logo.svg" alt="" class="navbar-logo dark-content"></a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Dr Dominic Royé</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
<li class="nav-item">
    <a class="nav-link" href="../../about/index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blog/index.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../publication/index.html"> 
<span class="menu-text">Publications</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../bioclim/index.html"> 
<span class="menu-text">Bioclim</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../project/index.html"> 
<span class="menu-text">Data Viz</span></a>
  </li>  
</ul>
</div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content"><!-- source: https://github.com/gadenbuie/garrickadenbuie-com/blob/main/_partials/title-block-link-buttons/title-block.html --><!-- 
<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title"> 
--><!-- <header id="title-block-header" class="quarto-title-block default page-columns"> --><!-- <div class="quarto-title page-columns page-full featured-image p-4" style="background-image: url(featured.png), url(featured.jpg), url(../featured.jpg);"> --><header id="title-block-header" class="quarto-title-block default page-columns"><div id="title-block-header-title" class="quarto-title page-columns page-full page-layout-full featured-image p-4" style="background-image: url(featured.png), url(featured.jpg), url(../featured.jpg);">
<h1 class="title">Downscaling solar radiation in the Canary Islands with GAM</h1>
    <div class="quarto-categories">
        <div class="quarto-category">Spatial analysis</div>
        <div class="quarto-category">Geostatistics</div>
        <div class="quarto-category">R:Advanced</div>
        <div class="quarto-category">GAM</div>
        <div class="quarto-category">R</div>
        <div class="quarto-category">terra</div>
        <div class="quarto-category">downscaling</div>
      </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Dominic Royé </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 2, 2026</p>
    </div>
  </div>
  
    
  </div>
  



</header>
<div class="no-row-height column-margin column-container"><div class="">
<p><a href="featured.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1"><img src="featured.png" class="img-fluid"></a></p>
</div></div><p>I’ve been meaning to write a post on how we can push interpolation and downscaling— beyond the usual tools like linear regression or kriging when dealing with climate data. This post illustrates a statistical downscaling workflow for monthly radiation over the Canary Islands using a Generalized Additive Model (GAM). We start from a coarse ~4km signal, learn its relationship with topography and MODIS cloudiness, and then predict to a finer 1km grid. The approach is intentionally lightweight: a single-month example (January) and a compact set of predictors.</p>
<p>The Canary Islands offer a particularly compelling test case for downscaling because of their extremely complex orography and sharp local climate gradients. With steep volcanic relief rising from sea level to over 3,000m in very short horizontal distances, conditions can change dramatically within a few kilometres. However, the native Meteosat resolution of around 4km smooths out much of this spatial variability, blending together zones that in reality experience very different levels of cloudiness and thus solar radiation.</p>
<blockquote class="blockquote">
<p><strong>Tip</strong><br>
GAMs are flexible enough to capture <strong>non-linear</strong> effects and <strong>interactions</strong> (e.g., cloudiness × elevation) while remaining interpretable thanks to smooth terms.</p>
</blockquote>
<section id="packages" class="level2"><h2 class="anchored" data-anchor-id="packages">Packages</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">Package</th>
<th style="text-align: left;">Description</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">terra</td>
<td style="text-align: left;">The modern standard for spatial data analysis, providing high-performance methods for manipulating and modeling raster and vector data.</td>
</tr>
<tr class="even">
<td style="text-align: left;">sf</td>
<td style="text-align: left;">Provides “Simple Features” support for R, serving as the core package for handling and transforming vector-based geographic data (points, lines, polygons).</td>
</tr>
<tr class="odd">
<td style="text-align: left;">tidyverse</td>
<td style="text-align: left;">A foundational collection of packages (visualization, manipulation): ggplot2, dplyr, purrr, etc., designed for cohesive data science workflows.</td>
</tr>
<tr class="even">
<td style="text-align: left;">fs</td>
<td style="text-align: left;">Offers a cross-platform, uniform interface for file system operations, making path and file management more robust and readable.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mgcv</td>
<td style="text-align: left;">The industry-standard library for Generalized Additive Models (GAMs).</td>
</tr>
<tr class="even">
<td style="text-align: left;">elevatr</td>
<td style="text-align: left;">Provides access to global elevation data APIs, simplifying the automated download of Digital Elevation Models (DEM) for any study area.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mapSpain</td>
<td style="text-align: left;">A specialized tool for downloading high-quality administrative boundaries and cartographic data for Spain at multiple scales.</td>
</tr>
<tr class="even">
<td style="text-align: left;">tidyterra</td>
<td style="text-align: left;">Bridges the gap between <strong>terra</strong> and <strong>ggplot2</strong>, allowing for the direct and efficient visualization of SpatRaster and SpatVector objects.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">patchwork</td>
<td style="text-align: left;">A powerful layout tool that makes it incredibly simple to combine separate ggplot objects into a single, cohesive, publication-ready figure.</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">pkgs</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"terra"</span>,<span class="st">"sf"</span>,<span class="st">"tidyverse"</span>,<span class="st">"fs"</span>,<span class="st">"mgcv"</span>,<span class="st">"elevatr"</span>,<span class="st">"mapSpain"</span>, <span class="st">"patchwork"</span>, <span class="st">"tidyterra"</span><span class="op">)</span></span>
<span><span class="kw">for</span><span class="op">(</span><span class="va">p</span> <span class="kw">in</span> <span class="va">pkgs</span><span class="op">)</span> <span class="kw">if</span><span class="op">(</span><span class="op">!</span><span class="kw"><a href="https://rdrr.io/r/base/library.html">require</a></span><span class="op">(</span><span class="va">p</span>, character.only <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span> <span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="va">p</span><span class="op">)</span></span>
<span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://rspatial.org/">terra</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://r-spatial.github.io/sf/">sf</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://fs.r-lib.org">fs</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">mgcv</span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/usepa/elevatr/">elevatr</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ropenspain.github.io/mapSpain/">mapSpain</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dieghernan.github.io/tidyterra/">tidyterra</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://patchwork.data-imaginist.com">patchwork</a></span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section><section id="study-area-and-inputs" class="level2 page-columns page-full"><h2 class="anchored" data-anchor-id="study-area-and-inputs">Study area and inputs</h2>
<p>We import the Canary geometry with names for each Island, transform it to <code>EPSG:4083</code>, and load: - <strong>Cloudiness</strong> (MODIS proxy, see below) at ~1km. - <strong>Total sunhours</strong> (coarse, ~5km) for January 2026 (accessible via <a href="https://wui.cmsaf.eu/safira/action/viewProduktHome?menuName=PRODUKT_HOME">EUMETSAT - CMSAF</a>) - <strong>Elevation</strong> from <code>elevatr</code> package to derive slope and aspect at both 5km and 1km.</p>
<p>To derive the monthly cloudiness climatology from MODIS, I combined the Terra (morning) and Aqua (afternoon) surface reflectance collections in Google Earth Engine (<a href="https://code.earthengine.google.com/8c9840e4a6fce8c8d68246409763afd4">script</a>) and extracted a simple cloud-state indicator from the state_1km QA band. Pixels flagged as clear, mixed, or cloudy were converted to continuous values (0, 0.5, 1), while missing or masked states were excluded. The result is a 1‑km image summarising the average monthly cloud conditions over the region for January 2026.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>You can download the used datasets <a href="../../assets/www/data_gam.zip">here</a>.</p>
</div>
</div>
<div class="cell page-columns page-full">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Canary Islands geometry </span></span>
<span><span class="va">can</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_read.html">st_read</a></span><span class="op">(</span><span class="st">"islas_20170101_generalizada.json"</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `islas_20170101_generalizada' from data source 
  `C:\Users\xeo19\Nextcloud\New web\blog\canary-gam-downscaling\islas_20170101_generalizada.json' 
  using driver `GeoJSON'
Simple feature collection with 7 features and 15 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: -18.16083 ymin: 27.63773 xmax: -13.33512 ymax: 29.41606
Geodetic CRS:  WGS 84</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">can</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_transform.html">st_transform</a></span><span class="op">(</span><span class="va">can</span>, <span class="fl">4083</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># MODIS ~1 km cloudiness</span></span>
<span><span class="va">modis_1km</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rspatial.github.io/terra/reference/rast.html">rast</a></span><span class="op">(</span><span class="st">"cloud_jan_26.tif"</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rspatial.github.io/terra/reference/project.html">project</a></span><span class="op">(</span><span class="st">"EPSG:4083"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rspatial.github.io/terra/reference/plot.html">plot</a></span><span class="op">(</span><span class="va">modis_1km</span><span class="op">)</span> <span class="co"># rate 0 to 1 = (0-100%)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

<div class="no-row-height column-margin column-container"><div class="cell-output-display">
<div>
<figure class="figure"><p><a href="index_files/figure-html/unnamed-chunk-2-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2"><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div></div></div>
<div class="cell page-columns page-full">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># rasterize and assign island label at 1 km</span></span>
<span><span class="va">isla_rast_1km</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rspatial.github.io/terra/reference/rasterize.html">rasterize</a></span><span class="op">(</span><span class="va">can</span>, <span class="fu"><a href="https://rspatial.github.io/terra/reference/rast.html">rast</a></span><span class="op">(</span><span class="va">modis_1km</span><span class="op">)</span>, field <span class="op">=</span> <span class="st">"etiqueta"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rspatial.github.io/terra/reference/plot.html">plot</a></span><span class="op">(</span><span class="va">isla_rast_1km</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

<div class="no-row-height column-margin column-container"><div class="cell-output-display">
<div>
<figure class="figure"><p><a href="index_files/figure-html/unnamed-chunk-3-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3"><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div></div></div>
<div class="cell page-columns page-full">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Coarse sunhours for Jan 2026 (~5 km): </span></span>
<span><span class="va">sol_4km</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rspatial.github.io/terra/reference/rast.html">rast</a></span><span class="op">(</span><span class="st">"SDUms202601010000004UD10001I1UD.nc"</span>, subds <span class="op">=</span> <span class="st">"SDU"</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rspatial.github.io/terra/reference/project.html">project</a></span><span class="op">(</span><span class="st">"EPSG:4083"</span><span class="op">)</span></span>
<span><span class="va">sol_4km</span> <span class="op">&lt;-</span> <span class="va">sol_4km</span><span class="op">/</span><span class="fl">10</span> <span class="co"># terra si using a factor from the nc file when we project</span></span>
<span><span class="fu"><a href="https://rspatial.github.io/terra/reference/plot.html">plot</a></span><span class="op">(</span><span class="va">sol_4km</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

<div class="no-row-height column-margin column-container"><div class="cell-output-display">
<div>
<figure class="figure"><p><a href="index_files/figure-html/unnamed-chunk-4-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4"><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div></div></div>
<div class="cell page-columns page-full">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># resample cloudiness at 4 km</span></span>
<span><span class="va">modis_4km</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rspatial.github.io/terra/reference/resample.html">resample</a></span><span class="op">(</span><span class="va">modis_1km</span>, <span class="va">sol_4km</span>, method <span class="op">=</span> <span class="st">"bilinear"</span><span class="op">)</span></span>
<span><span class="va">isla_rast_4km</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rspatial.github.io/terra/reference/rasterize.html">rasterize</a></span><span class="op">(</span><span class="va">can</span>, <span class="fu"><a href="https://rspatial.github.io/terra/reference/rast.html">rast</a></span><span class="op">(</span><span class="va">sol_4km</span><span class="op">)</span>, field <span class="op">=</span> <span class="st">"etiqueta"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Elevation and terrain metrics at both resolutions</span></span>
<span><span class="va">elev</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/elevatr/man/get_elev_raster.html">get_elev_raster</a></span><span class="op">(</span><span class="va">modis_4km</span>, z <span class="op">=</span> <span class="fl">7</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rspatial.github.io/terra/reference/rast.html">rast</a></span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rspatial.github.io/terra/reference/project.html">project</a></span><span class="op">(</span><span class="st">"EPSG:4083"</span><span class="op">)</span></span>
<span><span class="va">elev_4km</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rspatial.github.io/terra/reference/resample.html">resample</a></span><span class="op">(</span><span class="va">elev</span>, <span class="va">sol_4km</span>, method <span class="op">=</span> <span class="st">"bilinear"</span><span class="op">)</span></span>
<span><span class="va">elev_1km</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rspatial.github.io/terra/reference/resample.html">resample</a></span><span class="op">(</span><span class="va">elev</span>, <span class="va">modis_1km</span>, method <span class="op">=</span> <span class="st">"bilinear"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rspatial.github.io/terra/reference/plot.html">plot</a></span><span class="op">(</span><span class="va">elev_1km</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

<div class="no-row-height column-margin column-container"><div class="cell-output-display">
<div>
<figure class="figure"><p><a href="index_files/figure-html/unnamed-chunk-5-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5"><img src="index_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div></div></div>
<div class="cell page-columns page-full">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">asp_1km</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rspatial.github.io/terra/reference/terrain.html">terrain</a></span><span class="op">(</span><span class="va">elev_1km</span>, <span class="st">"aspect"</span>, unit <span class="op">=</span> <span class="st">"radians"</span><span class="op">)</span> </span>
<span><span class="fu"><a href="https://rspatial.github.io/terra/reference/plot.html">plot</a></span><span class="op">(</span><span class="va">asp_1km</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

<div class="no-row-height column-margin column-container"><div class="cell-output-display">
<div>
<figure class="figure"><p><a href="index_files/figure-html/unnamed-chunk-6-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6"><img src="index_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div></div></div>
<div class="cell page-columns page-full">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">sl_1km</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rspatial.github.io/terra/reference/terrain.html">terrain</a></span><span class="op">(</span><span class="va">elev_1km</span>, <span class="st">"slope"</span><span class="op">)</span> </span>
<span><span class="fu"><a href="https://rspatial.github.io/terra/reference/plot.html">plot</a></span><span class="op">(</span><span class="va">sl_1km</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

<div class="no-row-height column-margin column-container"><div class="cell-output-display">
<div>
<figure class="figure"><p><a href="index_files/figure-html/unnamed-chunk-7-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7"><img src="index_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div></div><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">asp_4km</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rspatial.github.io/terra/reference/resample.html">resample</a></span><span class="op">(</span><span class="va">asp_1km</span>, <span class="va">sol_4km</span>, method <span class="op">=</span> <span class="st">"bilinear"</span><span class="op">)</span></span>
<span><span class="va">sl_4km</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rspatial.github.io/terra/reference/resample.html">resample</a></span><span class="op">(</span><span class="va">sl_1km</span>, <span class="va">sol_4km</span>, method <span class="op">=</span> <span class="st">"bilinear"</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Computing slope or aspect directly at 4km loses important terrain information because the coarse resolution smooths out real topographic variability. By deriving these metrics at 1km first, you preserve the finer‑scale gradients before aggregating them.</p>
<p>For a discrete variable like the islands, rasterizing directly at 4km is appropriate because the categories should not be smoothed or interpolated. Resampling a discrete class would mix labels, so rasterization at the target resolution preserves the original categorical boundaries.</p>
</div>
</div>
</section><section id="build-modelling-tables" class="level2"><h2 class="anchored" data-anchor-id="build-modelling-tables">Build modelling tables</h2>
<p>We assemble a training table at 4km (response + predictors) and a prediction table at 1km (predictors only). For convenience we mask to the islands polygon.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Training stack (4 km)</span></span>
<span><span class="va">lay</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">sol_4km</span>, <span class="va">modis_4km</span>, <span class="va">elev_4km</span>, <span class="va">sl_4km</span>, <span class="va">asp_4km</span>, <span class="va">isla_rast_4km</span><span class="op">)</span></span>
<span><span class="va">lay</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rspatial.github.io/terra/reference/mask.html">mask</a></span><span class="op">(</span><span class="va">lay</span>, <span class="va">can</span><span class="op">)</span></span>
<span></span>
<span><span class="va">df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rspatial.github.io/terra/reference/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="va">lay</span>, xy <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rspatial.github.io/terra/reference/names.html">names</a></span><span class="op">(</span><span class="va">df</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"x"</span>,<span class="st">"y"</span>,<span class="st">"sunhr"</span>,<span class="st">"cloud"</span>,<span class="st">"elev"</span>,<span class="st">"sl"</span>,<span class="st">"asp"</span>,<span class="st">"isl"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span><span class="va">df</span>, sin_asp <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Trig.html">sin</a></span><span class="op">(</span><span class="va">asp</span><span class="op">)</span>, cos_asp <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Trig.html">cos</a></span><span class="op">(</span><span class="va">asp</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Prediction (1 km)</span></span>
<span><span class="va">lay_pred</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">modis_1km</span>, <span class="va">elev_1km</span>, <span class="va">sl_1km</span>, <span class="va">asp_1km</span>, <span class="va">isla_rast_1km</span><span class="op">)</span></span>
<span><span class="va">lay_pred</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rspatial.github.io/terra/reference/mask.html">mask</a></span><span class="op">(</span><span class="va">lay_pred</span>, <span class="va">can</span><span class="op">)</span></span>
<span></span>
<span><span class="va">df_pred</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rspatial.github.io/terra/reference/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="va">lay_pred</span>, xy <span class="op">=</span> <span class="cn">TRUE</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rspatial.github.io/terra/reference/names.html">names</a></span><span class="op">(</span><span class="va">df_pred</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"x"</span>,<span class="st">"y"</span>,<span class="st">"cloud"</span>,<span class="st">"elev"</span>,<span class="st">"sl"</span>,<span class="st">"asp"</span>, <span class="st">"isl"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">df_pred</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span><span class="va">df_pred</span>, sin_asp <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Trig.html">sin</a></span><span class="op">(</span><span class="va">asp</span><span class="op">)</span>, cos_asp <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Trig.html">cos</a></span><span class="op">(</span><span class="va">asp</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">df</span><span class="op">)</span> </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 448
Columns: 10
$ x       &lt;dbl&gt; 640977.3, 645982.2, 640977.3, 645982.2, 640977.3, 645982.2, 65…
$ y       &lt;dbl&gt; 3252540, 3252540, 3242530, 3242530, 3237525, 3237525, 3237525,…
$ sunhr   &lt;dbl&gt; 213.5235, 217.2177, 213.2614, 215.2760, 210.9056, 211.9915, 21…
$ cloud   &lt;dbl&gt; 0.6225122, 0.5350854, 0.6715685, 0.6021773, 0.6255413, 0.58443…
$ elev    &lt;dbl&gt; -208.0254974, -6.7074027, -87.0284271, -8.0537682, -37.6034660…
$ sl      &lt;dbl&gt; 6.6919975, 2.1266482, 2.5276296, 0.8959233, 1.6019516, 1.79989…
$ asp     &lt;dbl&gt; 4.478906, 2.133024, 4.848343, 2.692572, 5.041506, 2.693937, 1.…
$ isl     &lt;fct&gt; NA, Lanzarote, NA, NA, NA, Lanzarote, NA, NA, NA, NA, Lanzarot…
$ sin_asp &lt;dbl&gt; -0.972866485, 0.846069840, -0.990772493, 0.434083800, -0.94632…
$ cos_asp &lt;dbl&gt; -0.23136724, -0.53307206, 0.13553549, -0.90087250, 0.32320739,…</code></pre>
</div>
</div>
</section><section id="model-gam-for-spatial-downscaling" class="level2"><h2 class="anchored" data-anchor-id="model-gam-for-spatial-downscaling">Model: GAM for spatial downscaling</h2>
<p>In this section we progressively build the downscaling model, starting from a very simple baseline and incrementally adding predictors. This step‑by‑step approach helps illustrate how each component contributes to recovering the spatial variability that the native 4km Meteosat resolution cannot resolve over the highly complex orography of the Canary Islands.</p>
<section id="baseline-model-only-spatial-coordinates" class="level3"><h3 class="anchored" data-anchor-id="baseline-model-only-spatial-coordinates">1. Baseline model: only spatial coordinates</h3>
<p>We begin with the simplest possible GAM: a bivariate smooth over the coordinates. This model captures only broad spatial gradients and serves as a lower bound for performance. Think of these as our “foundation” before adding complex physical variables like cloud cover or elevation.</p>
<ol type="1">
<li><p>The first model is the simplest spatial approach. It treats the entire archipelago as a single continuous surface. It uses a bivariate smooth <span class="math inline">\(s(x, y)\)</span> to find a general heat map of sunshine hours across all islands. But it assumes that the climate changes smoothly over the ocean between islands. In reality, a mountain in Tenerife creates a microclimate that has nothing to do with the flat plains of Lanzarote.</p></li>
<li><p>In the second model, we acknowledge that each island is its own “climatic universe.” <code>isl - 1</code>: We remove the global intercept so each island gets its own baseline sunshine level. <code>by = isl</code>: give each island its own independent spatial surface <span class="math inline">\(s(x, y)\)</span>. This model respects the geographical fragmentation of the archipelago. It allows Tenerife to have a complex, curvy sunshine pattern while letting Lanzarote remain flatter and more uniform.</p></li>
</ol>
<p>A critical decision in spatial GAMs is setting the basis dimension (<span class="math inline">\(k\)</span>), which determines the maximum possible complexity of the smooth terms. For our island-specific model, we set <span class="math inline">\(k = 12\)</span> for each <span class="math inline">\(s(x, y)\)</span> term. In islands with dramatic orography like Tenerife or Gran Canaria, a low <span class="math inline">\(k\)</span> (e.g., <span class="math inline">\(k=5\)</span>) would “oversmooth” the results. One of the strengths of the mgcv framework is that <span class="math inline">\(k\)</span> only sets the upper limit of complexity. The model uses penalized likelihood (REML) to dampen the smooth if it doesn’t find enough signal. We see this clearly in Lanzarote, where despite having <span class="math inline">\(k=12\)</span> available, the model only used 2.00 DF, identifying the island’s sunshine pattern as a simple linear plane.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># basic model</span></span>
<span><span class="va">gam_base1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/gam.html">gam</a></span><span class="op">(</span></span>
<span>  <span class="va">sunhr</span> <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/s.html">s</a></span><span class="op">(</span><span class="va">x</span>, <span class="va">y</span><span class="op">)</span>, </span>
<span>  data   <span class="op">=</span> <span class="va">df</span>,</span>
<span>  method <span class="op">=</span> <span class="st">"REML"</span></span>
<span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rspatial.github.io/terra/reference/summary.html">summary</a></span><span class="op">(</span><span class="va">gam_base1</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Family: gaussian 
Link function: identity 

Formula:
sunhr ~ s(x, y)

Parametric coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 204.6858     0.4876   419.8   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Approximate significance of smooth terms:
         edf Ref.df     F p-value    
s(x,y) 28.47  28.98 83.49  &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

R-sq.(adj) =  0.843   Deviance explained = 85.3%
-REML = 1744.6  Scale est. = 106.51    n = 448</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># basic model with </span></span>
<span><span class="va">gam_base2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/gam.html">gam</a></span><span class="op">(</span></span>
<span>  <span class="va">sunhr</span> <span class="op">~</span> <span class="va">isl</span> <span class="op">-</span> <span class="fl">1</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/s.html">s</a></span><span class="op">(</span><span class="va">x</span>, <span class="va">y</span>, by <span class="op">=</span> <span class="va">isl</span> , k <span class="op">=</span> <span class="fl">12</span><span class="op">)</span>, </span>
<span>  data   <span class="op">=</span> <span class="va">df</span>,</span>
<span>  method <span class="op">=</span> <span class="st">"REML"</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rspatial.github.io/terra/reference/summary.html">summary</a></span><span class="op">(</span><span class="va">gam_base2</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Family: gaussian 
Link function: identity 

Formula:
sunhr ~ isl - 1 + s(x, y, by = isl, k = 12)

Parametric coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)   
islEl Hierro     -11657.821   5006.902  -2.328  0.02068 * 
islFuerteventura     -1.797    155.364  -0.012  0.99078   
islGran Canaria     787.365    328.479   2.397  0.01725 * 
islLa Gomera       2282.051   3245.040   0.703  0.48255   
islLa Palma        -182.159     59.261  -3.074  0.00234 **
islLanzarote       -236.063    498.294  -0.474  0.63609   
islTenerife         440.446    381.691   1.154  0.24961   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Approximate significance of smooth terms:
                          edf Ref.df       F p-value    
s(x,y):islEl Hierro     3.887  4.345  21.262 &lt; 2e-16 ***
s(x,y):islFuerteventura 4.337  4.761  16.237 &lt; 2e-16 ***
s(x,y):islGran Canaria  6.509  6.991 107.383 &lt; 2e-16 ***
s(x,y):islLa Gomera     4.224  4.664  49.042 &lt; 2e-16 ***
s(x,y):islLa Palma      2.000  2.000  27.340 &lt; 2e-16 ***
s(x,y):islLanzarote     3.580  4.017   4.193 0.00333 ** 
s(x,y):islTenerife      7.411  7.922  93.978 &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

R-sq.(adj) =  0.904   Deviance explained = 91.6%
-REML = 992.67  Scale est. = 66.764    n = 293</code></pre>
</div>
</div>
<p><strong>What to check</strong></p>
<p>After running the initial spatial models, we can extract several key insights regarding the solar radiation field over the Canary Islands.</p>
<ul>
<li><p>Effective Degrees of Freedom (EDF): In the global model (gam_base1), the smooth <span class="math inline">\(s(x,y)\)</span> uses 28.4 EDF. This indicates a highly complex spatial surface where the model is forced to “stretch” a single spline across the entire archipelago to capture the sharp climatic contrasts between the islands.</p></li>
<li><p>Deviance Explained: The global baseline explains 85.3% of the deviance. While this is high for a starting point, moving to the island-specific model pushes this to 91.6%. This jump proves that the spatial organization of sunshine is not a single gradient, but a fragmented one dictated by the unique orography of each island.</p></li>
<li><p>Residual Variance (Scale Est.): The global model shows a scale estimate of 106.5. By simply allowing each island to have its own spatial trend, this variance drops drastically to 66.7. This significant reduction confirms that a large portion of the “error” in simpler models is actually just the ignored geographical boundaries between the islands.</p></li>
</ul>
<p>Despite the high deviance explained (over 91% in the best spatial case), clear residual structure remains. The k-index and diagnostic checks signal that while <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> capture the “where,” they don’t capture the “why”. The model is still missing the fundamental physical drivers: the Sea of Clouds (interaction between clouds and elevation) and the terrain geometry (slope and aspect). These baselines confirm that while the 5km Meteosat signal has a strong spatial component, we need additional physical predictors to recover the finer-scale variability that coordinates alone cannot explain.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># some diagnostic plots and stats</span></span>
<span><span class="fu"><a href="https://rspatial.github.io/terra/reference/plot.html">plot</a></span><span class="op">(</span><span class="va">gam_base2</span>, shade <span class="op">=</span> <span class="cn">TRUE</span>, pages <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="index_files/figure-html/unnamed-chunk-10-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8"><img src="index_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="index_files/figure-html/unnamed-chunk-10-2.png" class="lightbox" data-gallery="quarto-lightbox-gallery-9"><img src="index_files/figure-html/unnamed-chunk-10-2.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/gam.check.html">gam.check</a></span><span class="op">(</span><span class="va">gam_base2</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="index_files/figure-html/unnamed-chunk-10-3.png" class="lightbox" data-gallery="quarto-lightbox-gallery-10"><img src="index_files/figure-html/unnamed-chunk-10-3.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Method: REML   Optimizer: outer newton
full convergence after 16 iterations.
Gradient range [-5.429973e-06,3.753513e-05]
(score 992.6721 &amp; scale 66.76392).
Hessian positive definite, eigenvalue range [5.430171e-06,136.123].
Model rank =  84 / 84 

Basis dimension (k) checking results. Low p-value (k-index&lt;1) may
indicate that k is too low, especially if edf is close to k'.

                           k'   edf k-index p-value    
s(x,y):islEl Hierro     11.00  3.89     0.7  &lt;2e-16 ***
s(x,y):islFuerteventura 11.00  4.34     0.7  &lt;2e-16 ***
s(x,y):islGran Canaria  11.00  6.51     0.7  &lt;2e-16 ***
s(x,y):islLa Gomera     11.00  4.22     0.7  &lt;2e-16 ***
s(x,y):islLa Palma      11.00  2.00     0.7  &lt;2e-16 ***
s(x,y):islLanzarote     11.00  3.58     0.7  &lt;2e-16 ***
s(x,y):islTenerife      11.00  7.41     0.7  &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>A low k-index (&lt;1) means the basis dimension may be too low relative to the complexity of the underlying pattern. However, this is our baseline model, which intentionally uses only spatial coordinates. The fact that k appears borderline insufficient is actually expected, much of the spatial complexity is caused by other physical variables, not by pure spatial location.</p>
</section><section id="adding-the-first-physical-driver-cloudiness" class="level3"><h3 class="anchored" data-anchor-id="adding-the-first-physical-driver-cloudiness">2. Adding the first physical driver: cloudiness</h3>
<p>Next we incorporate MODIS cloudiness, our likely strongest predictor for solar radiation from a physical point of view. This reveals how much fine‑scale variability can be explained by cloud patterns alone.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">gam_cloud</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/gam.html">gam</a></span><span class="op">(</span></span>
<span>  <span class="va">sunhr</span> <span class="op">~</span> <span class="va">isl</span> <span class="op">-</span> <span class="fl">1</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/s.html">s</a></span><span class="op">(</span><span class="va">cloud</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/s.html">s</a></span><span class="op">(</span><span class="va">x</span>, <span class="va">y</span>, by <span class="op">=</span> <span class="va">isl</span> , k <span class="op">=</span> <span class="fl">12</span><span class="op">)</span>,</span>
<span>  data   <span class="op">=</span> <span class="va">df</span>,</span>
<span>  method <span class="op">=</span> <span class="st">"REML"</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rspatial.github.io/terra/reference/summary.html">summary</a></span><span class="op">(</span><span class="va">gam_cloud</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Family: gaussian 
Link function: identity 

Formula:
sunhr ~ isl - 1 + s(cloud) + s(x, y, by = isl, k = 12)

Parametric coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)   
islEl Hierro     -11319.68    4708.50  -2.404   0.0169 * 
islFuerteventura     16.60     129.30   0.128   0.8979   
islGran Canaria     631.39     236.53   2.669   0.0081 **
islLa Gomera       1519.12    2447.69   0.621   0.5354   
islLa Palma       -2454.90    1675.76  -1.465   0.1442   
islLanzarote        -72.03     382.49  -0.188   0.8508   
islTenerife         640.50     315.48   2.030   0.0434 * 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Approximate significance of smooth terms:
                          edf Ref.df      F  p-value    
s(cloud)                2.827  3.627 28.591  &lt; 2e-16 ***
s(x,y):islEl Hierro     4.082  4.545 16.003  &lt; 2e-16 ***
s(x,y):islFuerteventura 4.309  4.730  7.167 1.43e-05 ***
s(x,y):islGran Canaria  6.276  6.875 61.240  &lt; 2e-16 ***
s(x,y):islLa Gomera     4.114  4.571 37.703  &lt; 2e-16 ***
s(x,y):islLa Palma      5.036  5.551  9.956  &lt; 2e-16 ***
s(x,y):islLanzarote     3.448  3.890  6.286 0.000309 ***
s(x,y):islTenerife      7.356  7.870 37.097  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

R-sq.(adj) =  0.932   Deviance explained = 94.2%
-REML = 949.12  Scale est. = 47.106    n = 293</code></pre>
</div>
</div>
<p>The output shows a clear improvement over the baseline model that used only the spatial coordinates. The smooth term for cloudiness now has an edf of 2.83, which, in this stage of the modeling, indicates that the relationship between cloud cover and sunshine hours has evolved beyond a simple linear fit. While GAMs are designed to capture complex non-linearities, the model now identifies that even at this 5km scale, the decrease in solar radiation follows a more nuanced, curved trajectory as cloudiness increases.</p>
<p>The high F-statistic (28.59) and the extremely small p-value (&lt; 2e-16) confirm that cloudiness remains a dominant explanatory variable. Deviance explained remains high at 94.2%, while the residual variance (scale est.) is situated at 47.11. MODIS cloudiness carries information at 1km that Meteosat cannot resolve. Keep in mind that even when averaged to the 5km grid, cloudiness still helps distinguish areas that receive more or less solar radiation. However, because cloudiness alone does not yet encode elevation, slope, or exposure effects, the spatial smooths (<span class="math inline">\(s(x,y):isl\)</span>) still have to do a lot of work — ranging from an edf of 3.4 in Lanzarote to 7.3 in Tenerife — to capture the remaining orographic signals.</p>
<p>The diagnostic plots show the estimated smooth effect of cloudiness. The response decreases monotonically; the edf of 2.83 suggests a slight non-linear “bend” in the relationship at this resolution, making the model more robust than the previous linear assumption. The rug at the bottom indicates that the data cover the cloudiness range thoroughly, so the effect is well-supported across all atmospheric conditions. This non-linear baseline provides the perfect foundation before we introduce the interaction with elevation, which we expect will finally reveal the complex “Sea of Clouds” effect.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rspatial.github.io/terra/reference/plot.html">plot</a></span><span class="op">(</span><span class="va">gam_cloud</span>, pages <span class="op">=</span> <span class="fl">2</span>, shade <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="index_files/figure-html/unnamed-chunk-12-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-11"><img src="index_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="index_files/figure-html/unnamed-chunk-12-2.png" class="lightbox" data-gallery="quarto-lightbox-gallery-12"><img src="index_files/figure-html/unnamed-chunk-12-2.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/gam.check.html">gam.check</a></span><span class="op">(</span><span class="va">gam_cloud</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="index_files/figure-html/unnamed-chunk-12-3.png" class="lightbox" data-gallery="quarto-lightbox-gallery-13"><img src="index_files/figure-html/unnamed-chunk-12-3.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Method: REML   Optimizer: outer newton
full convergence after 19 iterations.
Gradient range [-2.129741e-06,6.316135e-09]
(score 949.1164 &amp; scale 47.10584).
Hessian positive definite, eigenvalue range [0.2894498,135.6413].
Model rank =  93 / 93 

Basis dimension (k) checking results. Low p-value (k-index&lt;1) may
indicate that k is too low, especially if edf is close to k'.

                           k'   edf k-index p-value    
s(cloud)                 9.00  2.83    1.05    0.81    
s(x,y):islEl Hierro     11.00  4.08    0.82  &lt;2e-16 ***
s(x,y):islFuerteventura 11.00  4.31    0.82  &lt;2e-16 ***
s(x,y):islGran Canaria  11.00  6.28    0.82  &lt;2e-16 ***
s(x,y):islLa Gomera     11.00  4.11    0.82  &lt;2e-16 ***
s(x,y):islLa Palma      11.00  5.04    0.82  &lt;2e-16 ***
s(x,y):islLanzarote     11.00  3.45    0.82  &lt;2e-16 ***
s(x,y):islTenerife      11.00  7.36    0.82  &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section><section id="full-downscaling-model" class="level3"><h3 class="anchored" data-anchor-id="full-downscaling-model">3. Full downscaling model</h3>
<p>Finally we build the complete model used for the 1km downscaling.<br>
This model includes:</p>
<ul>
<li>
<strong>island factor</strong> (<code>isl</code>) to capture structural differences between islands,<br>
</li>
<li>
<strong>cloud × elevation interaction</strong> via a tensor-product smooth (<code>te(cloud, elev)</code>),</li>
<li>
<strong>slope effect</strong> (<code>s(sl)</code>),<br>
</li>
<li>
<strong>aspect effect</strong> (<code>s(cos_asp, sin_asp)</code>) As it is a circular variable. We transform it into its sine and cosine components avoiding artificial discontinuities at 0/2π,</li>
<li>
<strong>residual spatial structure</strong> through <code>s(x, y, by = isl, k = 12)</code>.</li>
</ul>
<p>The term <code><a href="https://rdrr.io/pkg/mgcv/man/te.html">te()</a></code> allows the effect of cloudiness on solar radiation to change depending on elevation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">gam_fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/gam.html">gam</a></span><span class="op">(</span></span>
<span>  <span class="va">sunhr</span> <span class="op">~</span> <span class="va">isl</span> <span class="op">-</span> <span class="fl">1</span>  <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/te.html">te</a></span><span class="op">(</span><span class="va">cloud</span>, <span class="va">elev</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/s.html">s</a></span><span class="op">(</span><span class="va">sl</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/s.html">s</a></span><span class="op">(</span><span class="va">cos_asp</span>, <span class="va">sin_asp</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/s.html">s</a></span><span class="op">(</span><span class="va">x</span>, <span class="va">y</span>, by <span class="op">=</span> <span class="va">isl</span> , k <span class="op">=</span> <span class="fl">12</span><span class="op">)</span>,</span>
<span>  data   <span class="op">=</span> <span class="va">df</span>,</span>
<span>  method <span class="op">=</span> <span class="st">"REML"</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rspatial.github.io/terra/reference/summary.html">summary</a></span><span class="op">(</span><span class="va">gam_fit</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Family: gaussian 
Link function: identity 

Formula:
sunhr ~ isl - 1 + te(cloud, elev) + s(sl) + s(cos_asp, sin_asp) + 
    s(x, y, by = isl, k = 12)

Parametric coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)  
islEl Hierro     -6019.68    3403.33  -1.769   0.0782 .
islFuerteventura    23.50     138.85   0.169   0.8658  
islGran Canaria    462.04     200.88   2.300   0.0223 *
islLa Gomera      1339.62    2087.79   0.642   0.5217  
islLa Palma        -72.64      60.55  -1.200   0.2314  
islLanzarote       -27.08     374.65  -0.072   0.9424  
islTenerife        765.79     326.31   2.347   0.0197 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Approximate significance of smooth terms:
                          edf Ref.df      F  p-value    
te(cloud,elev)          7.869  9.457 14.374  &lt; 2e-16 ***
s(sl)                   2.572  3.315  1.633   0.1895    
s(cos_asp,sin_asp)      2.000  2.001  4.034   0.0189 *  
s(x,y):islEl Hierro     3.538  3.944 18.541  &lt; 2e-16 ***
s(x,y):islFuerteventura 4.393  4.799  6.876 1.13e-05 ***
s(x,y):islGran Canaria  5.885  6.628 41.485  &lt; 2e-16 ***
s(x,y):islLa Gomera     3.966  4.432 40.582  &lt; 2e-16 ***
s(x,y):islLa Palma      2.001  2.001 16.519 2.49e-07 ***
s(x,y):islLanzarote     3.431  3.871  3.901   0.0118 *  
s(x,y):islTenerife      7.324  7.839 39.272  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

R-sq.(adj) =  0.937   Deviance explained = 94.8%
-REML = 924.56  Scale est. = 43.435    n = 293</code></pre>
</div>
</div>
<p>The output shows a substantial improvement over the intermediate models, confirming that the combination of cloud–topography interactions and fine-scale terrain variables is essential for explaining solar-radiation variability in the Canary Islands. The model now reaches a Deviance Explained of 94.8%, with a reduced scale estimate of 43.44.</p>
<ul>
<li><p>ISL: The island factor (isl - 1) absorbs structural differences between islands not captured by the smooth terms. Several islands show statistically significant departures; for instance, Tenerife and Gran Canaria show positive, significant adjustments (<span class="math inline">\(p &lt; 0.05\)</span>), setting unique baselines that reflect their specific atmospheric and geographic contexts.</p></li>
<li><p>CLOUD × ELEV: The tensor-product te(cloud, elev) is highly significant (<span class="math inline">\(p &lt; 2e-16\)</span>) and has an edf of 7.87. This demonstrates that the joint effect of cloudiness and elevation is genuinely non-linear and more complex than previously estimated. It effectively captures the “Sea of Clouds” phenomenon, where high-altitude peaks “pierce” the inversion layer—a central feature of the Canarian climate where solar radiation remains high at altitude despite heavy cloud cover in the mid-layers.</p></li>
<li><p>SL and ASP: The terrain variables provide the final layer of local refinement. The aspect s(cos_asp, sin_asp) is statistically significant (edf = 2.0, <span class="math inline">\(p = 0.0189\)</span>), capturing the cyclic effect of orientation-driven exposure, such as the contrast between north-facing and south-facing slopes. While the slope s(sl) shows an edf of 2.57, its current significance (<span class="math inline">\(p = 0.1895\)</span>) suggests that at this 5km scale, orientation (aspect) is a more dominant driver of radiation variability than the gradient itself. However, the slope slightly improves the model fit, although not in a statistically significant way (p ≈ 0.10). The ANOVA test indicates that it still contributes something to the model, and since we have built a causal (i.e.&nbsp;physically motivated) model, it makes sense to retain it.</p></li>
<li><p>Spatial Smooths: The island-specific spatial smooths s(x,y):isl remain highly significant, but their complexity has shifted. For La Palma, the edf has dropped to 2.0, indicating that the new topography terms now explain the variance that was previously handled by the spatial coordinates alone. Conversely, Tenerife still requires a high edf (7.32), reflecting the extreme orographic complexity that continues to challenge the model’s resolution.</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rspatial.github.io/terra/reference/plot.html">plot</a></span><span class="op">(</span><span class="va">gam_fit</span>, shade <span class="op">=</span> <span class="cn">TRUE</span>, pages <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="index_files/figure-html/unnamed-chunk-14-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-14"><img src="index_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="index_files/figure-html/unnamed-chunk-14-2.png" class="lightbox" data-gallery="quarto-lightbox-gallery-15"><img src="index_files/figure-html/unnamed-chunk-14-2.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/gam.check.html">gam.check</a></span><span class="op">(</span><span class="va">gam_fit</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="index_files/figure-html/unnamed-chunk-14-3.png" class="lightbox" data-gallery="quarto-lightbox-gallery-16"><img src="index_files/figure-html/unnamed-chunk-14-3.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Method: REML   Optimizer: outer newton
full convergence after 23 iterations.
Gradient range [-0.0002344738,0.0001139124]
(score 924.5562 &amp; scale 43.43539).
Hessian positive definite, eigenvalue range [3.405437e-05,133.1409].
Model rank =  146 / 146 

Basis dimension (k) checking results. Low p-value (k-index&lt;1) may
indicate that k is too low, especially if edf is close to k'.

                           k'   edf k-index p-value    
te(cloud,elev)          24.00  7.87    1.07   0.935    
s(sl)                    9.00  2.57    1.08   0.910    
s(cos_asp,sin_asp)      29.00  2.00    0.99   0.395    
s(x,y):islEl Hierro     11.00  3.54    0.87   0.005 ** 
s(x,y):islFuerteventura 11.00  4.39    0.87  &lt;2e-16 ***
s(x,y):islGran Canaria  11.00  5.89    0.87   0.010 ** 
s(x,y):islLa Gomera     11.00  3.97    0.87   0.010 ** 
s(x,y):islLa Palma      11.00  2.00    0.87  &lt;2e-16 ***
s(x,y):islLanzarote     11.00  3.43    0.87  &lt;2e-16 ***
s(x,y):islTenerife      11.00  7.32    0.87  &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The spatial surfaces remains highly significant, but it now performs a different role. With an Adjusted R-squared of 0.959 and a Deviance explained of 96.6%, the physical predictors have successfully explained the main share of the spatial structure. The remaining spatial smooths now capture only the residual, unmodelled variation unique to each island’s geography.</p>
<p>The sharp reduction in the scale estimate—dropping from 115.5 in the baseline to a mere 30.38 in this final version—highlights how much unexplained variability is removed by accounting for the interaction between clouds and terrain.</p>
<blockquote class="blockquote">
<p><strong>Why include <code>s(x, y)</code>?</strong><br>
Even after accounting for physics-like drivers, radiation shows residual patterns (exposure, mesoscale circulation, coastal gradients). A spatial smooth helps absorb that leftover structure and improves the sharpness of the 1km prediction.</p>
</blockquote>
</section></section><section id="predict-to-1km" class="level2"><h2 class="anchored" data-anchor-id="predict-to-1km">Predict to 1km</h2>
<p>We generate 1km predictions and rebuild a raster.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">pred_1km</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rspatial.github.io/terra/reference/predict.html">predict</a></span><span class="op">(</span><span class="va">gam_fit</span>, newdata <span class="op">=</span> <span class="va">df_pred</span>, type <span class="op">=</span> <span class="st">"response"</span><span class="op">)</span></span>
<span><span class="va">df_pred</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span><span class="va">df_pred</span>, pred <span class="op">=</span> <span class="va">pred_1km</span><span class="op">)</span></span>
<span></span>
<span><span class="va">sol_1km</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rspatial.github.io/terra/reference/rast.html">rast</a></span><span class="op">(</span><span class="va">df_pred</span><span class="op">[</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">2</span>, <span class="fl">10</span><span class="op">)</span><span class="op">]</span>, type <span class="op">=</span> <span class="st">"xyz"</span>, crs <span class="op">=</span> <span class="fu"><a href="https://rspatial.github.io/terra/reference/crs.html">crs</a></span><span class="op">(</span><span class="va">modis_1km</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rspatial.github.io/terra/reference/names.html">names</a></span><span class="op">(</span><span class="va">sol_1km</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="st">"sol_gam_1km"</span></span>
<span></span>
<span><span class="fu"><a href="https://rspatial.github.io/terra/reference/plot.html">plot</a></span><span class="op">(</span><span class="va">sol_1km</span>, main <span class="op">=</span> <span class="st">"Downscaled solar radiation (GAM, 1 km)"</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="index_files/figure-html/unnamed-chunk-15-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-17"><img src="index_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
</div>
</section><section id="optional-simple-cross-validation-cv" class="level2"><h2 class="anchored" data-anchor-id="optional-simple-cross-validation-cv">(Optional) Simple cross-validation (CV)</h2>
<p>I opted for stratified cross-validation instead of a spatial approach because the natural fragmentation of the archipelago already acts as a geographic barrier, reducing spatial autocorrelation between islands. This method ensures that even islands with a limited number of grid points are always represented in the training set, preventing model failure in low-density areas while still rigorously testing its ability to generalize to unsampled locations.</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># 1. Preparation</span></span>
<span><span class="va">folds</span> <span class="op">&lt;-</span> <span class="fl">5</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">123</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Create stratified groups by island to ensure all islands are represented in every fold</span></span>
<span><span class="va">df</span><span class="op">$</span><span class="va">group</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/split.html">unsplit</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span><span class="op">(</span><span class="fu"><a href="https://rspatial.github.io/terra/reference/split.html">split</a></span><span class="op">(</span><span class="va">df</span><span class="op">$</span><span class="va">isl</span>, <span class="va">df</span><span class="op">$</span><span class="va">isl</span><span class="op">)</span>, <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="va">folds</span>, length.out <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>, <span class="va">df</span><span class="op">$</span><span class="va">isl</span><span class="op">)</span></span>
<span></span>
<span><span class="va">mae_cv_list</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="kw">for</span><span class="op">(</span><span class="va">i</span> <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="va">folds</span><span class="op">)</span><span class="op">{</span></span>
<span>  <span class="co"># Split data into training and testing sets for the current fold</span></span>
<span>  <span class="va">train</span> <span class="op">&lt;-</span> <span class="va">df</span><span class="op">[</span><span class="va">df</span><span class="op">$</span><span class="va">group</span> <span class="op">!=</span> <span class="va">i</span>, <span class="op">]</span></span>
<span>  <span class="va">test</span>  <span class="op">&lt;-</span> <span class="va">df</span><span class="op">[</span><span class="va">df</span><span class="op">$</span><span class="va">group</span> <span class="op">==</span> <span class="va">i</span>, <span class="op">]</span></span>
<span>  </span>
<span>  <span class="co"># Dynamically adjust 'k' based on the island with the fewest points in the training set</span></span>
<span>  <span class="co"># This prevents model failure in islands with low station density</span></span>
<span>  <span class="va">min_n</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">train</span><span class="op">$</span><span class="va">isl</span><span class="op">)</span><span class="op">)</span></span>
<span>  <span class="va">k_val</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="fl">12</span>, <span class="va">min_n</span> <span class="op">-</span> <span class="fl">1</span><span class="op">)</span> </span>
<span>  </span>
<span>  <span class="co"># Attempt to fit the GAM model</span></span>
<span>  <span class="va">mod</span> <span class="op">&lt;-</span> <span class="kw"><a href="https://rdrr.io/r/base/try.html">try</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/gam.html">gam</a></span><span class="op">(</span><span class="va">sunhr</span> <span class="op">~</span> <span class="va">isl</span> <span class="op">-</span> <span class="fl">1</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/te.html">te</a></span><span class="op">(</span><span class="va">cloud</span>, <span class="va">elev</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/s.html">s</a></span><span class="op">(</span><span class="va">sl</span><span class="op">)</span> <span class="op">+</span> </span>
<span>                 <span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/s.html">s</a></span><span class="op">(</span><span class="va">cos_asp</span>, <span class="va">sin_asp</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/s.html">s</a></span><span class="op">(</span><span class="va">x</span>, <span class="va">y</span>, by <span class="op">=</span> <span class="va">isl</span>, k <span class="op">=</span> <span class="va">k_val</span><span class="op">)</span>,</span>
<span>                 data <span class="op">=</span> <span class="va">train</span>, method <span class="op">=</span> <span class="st">"REML"</span><span class="op">)</span>, silent <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span>  </span>
<span>  <span class="co"># If the model fit was successful, proceed to prediction</span></span>
<span>  <span class="kw">if</span><span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/class.html">inherits</a></span><span class="op">(</span><span class="va">mod</span>, <span class="st">"try-error"</span><span class="op">)</span><span class="op">)</span><span class="op">{</span></span>
<span>    <span class="va">preds</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rspatial.github.io/terra/reference/predict.html">predict</a></span><span class="op">(</span><span class="va">mod</span>, newdata <span class="op">=</span> <span class="va">test</span><span class="op">)</span></span>
<span>    </span>
<span>    <span class="co"># Calculate MAE for this iteration (removing any accidental NAs)</span></span>
<span>    <span class="va">mae_iter</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rspatial.github.io/terra/reference/summarize-generics.html">mean</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="va">test</span><span class="op">$</span><span class="va">sunhr</span> <span class="op">-</span> <span class="va">preds</span><span class="op">)</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span>    <span class="va">mae_cv_list</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">mae_cv_list</span>, <span class="va">mae_iter</span><span class="op">)</span></span>
<span>  <span class="op">}</span> <span class="kw">else</span> <span class="op">{</span></span>
<span>    <span class="co"># Provide a warning if the specific fold fails to converge</span></span>
<span>    <span class="kw"><a href="https://rdrr.io/r/base/warning.html">warning</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="st">"Fold"</span>, <span class="va">i</span>, <span class="st">"failed due to:"</span>, <span class="fu"><a href="https://rdrr.io/r/base/attr.html">attr</a></span><span class="op">(</span><span class="va">mod</span>, <span class="st">"condition"</span><span class="op">)</span><span class="op">$</span><span class="va">message</span><span class="op">)</span><span class="op">)</span></span>
<span>  <span class="op">}</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="co"># Final result: average the MAE across all successful folds</span></span>
<span><span class="va">final_mae_cv</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rspatial.github.io/terra/reference/summarize-generics.html">mean</a></span><span class="op">(</span><span class="va">mae_cv_list</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="st">"Cross-Validation MAE:"</span>, <span class="fu"><a href="https://rspatial.github.io/terra/reference/math-generics.html">round</a></span><span class="op">(</span><span class="va">final_mae_cv</span>, <span class="fl">4</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># MAE from GAM model</span></span>
<span><span class="va">pred</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rspatial.github.io/terra/reference/predict.html">predict</a></span><span class="op">(</span><span class="va">gam_fit</span>, type <span class="op">=</span> <span class="st">"response"</span><span class="op">)</span></span>
<span><span class="va">obs</span>  <span class="op">&lt;-</span> <span class="va">gam_fit</span><span class="op">$</span><span class="va">y</span></span>
<span></span>
<span><span class="co"># MAE</span></span>
<span><span class="va">MAE</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rspatial.github.io/terra/reference/summarize-generics.html">mean</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="va">pred</span> <span class="op">-</span> <span class="va">obs</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">MAE</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p><strong>Performance Comparison</strong>:</p>
<ul>
<li><p>Training MAE: 4.5 hours. This represents the model’s fit to the known data points, showing an extremely high precision in capturing the local nuances of the 5km field.</p></li>
<li><p>Cross-Validation MAE: 6.7 hours. As expected, the error increases slightly when predicting “unseen” locations. However, a jump of 2.2 hours is a sign of a highly robust model with no significant overfitting.</p></li>
</ul></section><section id="map-the-result" class="level2"><h2 class="anchored" data-anchor-id="map-the-result">Map the result</h2>
<p>Last but not least, the final map.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">g1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co"># 'geom_spatraster' is used for memory-efficient rendering of large rasters</span></span>
<span>  <span class="fu"><a href="https://dieghernan.github.io/tidyterra/reference/geom_spatraster.html">geom_spatraster</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">sol_1km</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">geom_sf</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">can</span>, fill <span class="op">=</span> <span class="cn">NA</span>, color <span class="op">=</span> <span class="st">"grey20"</span>, linewidth <span class="op">=</span> <span class="fl">0.3</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_brewer.html">scale_fill_distiller</a></span><span class="op">(</span>palette <span class="op">=</span> <span class="st">"YlOrRd"</span>, direction <span class="op">=</span> <span class="fl">1</span>, na.value <span class="op">=</span> <span class="cn">NA</span>, limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">124.9</span>, <span class="fl">265.8</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span></span>
<span>    title <span class="op">=</span> <span class="st">"High-Resolution Solar Mapping"</span>,</span>
<span>    subtitle <span class="op">=</span> <span class="st">"1km Prediction integrating cloud-topography interactions"</span>,</span>
<span>    caption <span class="op">=</span> <span class="st">"GAM Model Refined (Meteosat 4km + MODIS Cloud Data)"</span>,</span>
<span>    fill <span class="op">=</span> <span class="st">"h"</span>,</span>
<span>  <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_void</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span></span>
<span>    legend.position <span class="op">=</span> <span class="st">"top"</span>,</span>
<span>    legend.justification <span class="op">=</span> <span class="st">"left"</span>,</span>
<span>    legend.title.position <span class="op">=</span> <span class="st">"right"</span>,</span>
<span>    legend.key.width <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/grid/unit.html">unit</a></span><span class="op">(</span><span class="fl">3</span>, <span class="st">"lines"</span><span class="op">)</span>,</span>
<span>    legend.key.height <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/grid/unit.html">unit</a></span><span class="op">(</span><span class="fl">.5</span>, <span class="st">"lines"</span><span class="op">)</span>,</span>
<span>    legend.title <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>vjust <span class="op">=</span> <span class="fl">0.2</span>, size <span class="op">=</span> <span class="fl">9</span><span class="op">)</span>,</span>
<span>    plot.caption <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>hjust <span class="op">=</span> <span class="fl">0</span><span class="op">)</span>,</span>
<span>    plot.title <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>face <span class="op">=</span> <span class="st">"bold"</span><span class="op">)</span>,</span>
<span>    plot.subtitle <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>margin <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">margin</a></span><span class="op">(</span>b <span class="op">=</span> <span class="fl">10</span>, t <span class="op">=</span> <span class="fl">5</span><span class="op">)</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="va">map_data</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rspatial.github.io/terra/reference/crop.html">crop</a></span><span class="op">(</span><span class="va">sol_4km</span>, <span class="va">can</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rspatial.github.io/terra/reference/mask.html">mask</a></span><span class="op">(</span><span class="va">can</span><span class="op">)</span></span>
<span></span>
<span><span class="va">g2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co"># 'geom_spatraster' is used for memory-efficient rendering of large rasters</span></span>
<span>  <span class="fu"><a href="https://dieghernan.github.io/tidyterra/reference/geom_spatraster.html">geom_spatraster</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">map_data</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">geom_sf</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">can</span>, fill <span class="op">=</span> <span class="cn">NA</span>, color <span class="op">=</span> <span class="st">"grey20"</span>, linewidth <span class="op">=</span> <span class="fl">0.3</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_brewer.html">scale_fill_distiller</a></span><span class="op">(</span>palette <span class="op">=</span> <span class="st">"YlOrRd"</span>, direction <span class="op">=</span> <span class="fl">1</span>, na.value <span class="op">=</span> <span class="cn">NA</span>, limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">124.9</span>, <span class="fl">265.8</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/guides.html">guides</a></span><span class="op">(</span>fill <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span></span>
<span>    title <span class="op">=</span> <span class="st">"Original Meteosat dataset"</span>,</span>
<span>  <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_void</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span></span>
<span>    plot.title <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>margin <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">margin</a></span><span class="op">(</span>b <span class="op">=</span> <span class="fl">5</span>, t <span class="op">=</span> <span class="fl">10</span><span class="op">)</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="va">g1</span> <span class="op">/</span> <span class="va">g2</span> </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="index_files/figure-html/unnamed-chunk-17-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-18"><img src="index_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="960"></a></p>
</figure>
</div>
</div>
</div>


</section><a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a><div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" id="quarto-reuse"><h2 class="anchored quarto-appendix-heading">Reuse</h2><div class="quarto-appendix-contents"><div><a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a></div></div></section><section class="quarto-appendix-contents" id="quarto-citation"><h2 class="anchored quarto-appendix-heading">Citation</h2><div><div class="quarto-appendix-secondary-label">For attribution, please cite this work as:</div><div id="ref-royé2026" class="csl-entry quarto-appendix-citeas" role="listitem">
Royé, Dominic. 2026. <span>“Downscaling Solar Radiation in the Canary
Islands with GAM.”</span> March 2, 2026. <a href="https://dominicroye.github.io/blog/canary-gam-downscaling/">https://dominicroye.github.io/blog/canary-gam-downscaling/</a>.
</div></div></section></div></main><!-- /main --><div id="buymeacoffee" style="text-align: center; ">
    <a href="https://www.buymeacoffee.com/drxeo" target="_blank" data-original-href="https://www.buymeacoffee.com/drxeo"><img src="https://cdn.buymeacoffee.com/buttons/default-orange.png" alt="Buy Me A Coffee" height="41" width="174"></a>
</div>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/dominicroye\.github\.io\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2018-2025 Dominic Royé ∙ Made with <a href="https://quarto.org">Quarto</a></p>
</div>   
    <div class="nav-footer-center">
<p><a class="link-dark me-1" href="https://bsky.app/profile/drxeo.eu" title="Bluesky" target="_blank" rel="noopener"> <i class="fa-brands fa-bluesky" aria-label="bluesky"></i></a> <a class="link-dark me-1" href="https://www.linkedin.com/in/dominicroye/" title="LinkedIn" target="_blank" rel="noopener"> <i class="fa-brands fa-linkedin" aria-label="linkedin"></i></a> <a class="link-dark me-1" href="https://github.com/dominicroye/" title="github" target="_blank" rel="noopener"> <i class="fa-brands fa-github" aria-label="github"></i></a> <a class="link-dark me-1" href="https://orcid.org/0000-0002-5516-6396" title="orcid" target="_blank" rel="noopener"> <i class="ai  ai-orcid" aria-label="orcid"></i></a> <a class="link-dark me-1" href="https://scholar.google.es/citations?user=EoYa8jUAAAAJ&amp;hl=es" title="Google Scholar" target="_blank" rel="noopener"> <i class="ai  ai-google-scholar" aria-label="google-scholar"></i></a> <a class="link-dark me-1" href="https://www.researchgate.net/profile/Dominic-Roye?ev=hdr_xprf" title="github" target="_blank" rel="noopener"><i class="fa-brands fa-researchgate" aria-label="researchgate"></i></a></p>
</div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
<li class="nav-item">
    <a class="nav-link" href="../../contact.html">
<p>Contact</p>
</a>
  </li>  
</ul>
</div>
  </div>
</footer><script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>


</body></html>